### ISSUE TITLE
catkin build failed

### ISSUE THREAD

**Issue by xiangchen2011** [uzh-rpg/rpg_davis_simulator#3]
hello,when I catkin build the project the terminal show the following message after I git clone to my ubuntu :
================================================
➜  rpg_davis_simulator git:(master) ✗ catkin build dvs_simulator_py
--------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/xiangchen2011/Desktop/catkin_ws/devel:/opt/ros/kinetic
Workspace:                   /home/xiangchen2011/Desktop/rpg_davis_simulator
--------------------------------------------------------------------------------
Source Space:       [exists] /home/xiangchen2011/Desktop/rpg_davis_simulator/src
Log Space:         [missing] /home/xiangchen2011/Desktop/rpg_davis_simulator/logs
Build Space:        [exists] /home/xiangchen2011/Desktop/rpg_davis_simulator/build
Devel Space:        [exists] /home/xiangchen2011/Desktop/rpg_davis_simulator/devel
Install Space:      [unused] /home/xiangchen2011/Desktop/rpg_davis_simulator/install
DESTDIR:            [unused] None
--------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------------
Workspace configuration appears valid.
--------------------------------------------------------------------------------
[build] No packages were found in the source space '/home/xiangchen2011/Desktop/rpg_davis_simulator/src'
[build] Given package 'dvs_simulator_py' is not in the workspace

**Comment by sykiewang** [comment]
WARNING: Your workspace is not extending any other result space, but it is set
to use a `linked` devel space layout. This requires the `catkin` CMake package
in your source space in order to be built.
--------------------------------------------------------------------------------

[build] No packages were found in the source space '/home/xiangchen2011/Desktop/rpg_davis_simulator/src'
[build] Given package 'dvs_simulator_py' is not in the workspace

**Comment by joekh1** [comment]
hello sir! I have the same issue! can you please help in case you get the solution!

**Comment by Ehsan67m** [comment]
> hello sir! I have the same issue! can you please help in case you get the solution!

Did you find some solution?
