### ISSUE TITLE
Possible typo in prepare_dataset.py

### ISSUE THREAD

**Issue by francescomilano172** [uzh-rpg/rpg_davis_simulator#4]
Good morning,
Should `scene.render.resolution_x` be replaced with `scene.render.resolution_y` in the following line?
https://github.com/uzh-rpg/rpg_davis_simulator/blob/7dcbd0ca14bfa6fcb1dd8918c3b6767c28aef271/scripts/prepare_dataset.py#L64

**Comment by supitalp** [comment]
Yes, absolutely. Thanks for pointing this out, I will fix this asap.
